#!/usr/bin/with-contenv bash

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /config/sabnzbd ]; then
  echo "Creating /config/sabnzbd"
  mkdir -p /config/sabnzbd
  chown -R abc:abc /config/sabnzbd
fi
