#!/usr/bin/with-contenv bash

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /share/sabnzbd/config ]; then
  echo "Creating /share/sabnzbd/config"
  mkdir -p /share/sabnzbd/config
  chown -R abc:abc /share/sabnzbd/config
fi
